### ISSUE TITLE
No song is detected when listening to 'Tchaka' by Sydney Guillaume

### ISSUE THREAD

**Issue by dolphingarlic** [SwagLyrics/SwagLyrics-discord-bot#18]
![Image of the bug](https://i.imgur.com/Vjncr2Z.png)

This seems to happen only for this one specific song

**Comment by dolphingarlic** [comment]
See https://github.com/Rapptz/discord.py/issues/1738 for a possible explanation

**Comment by flabbet** [comment]
Well, this is out of our scope, I don't think we can do anything about that

**Comment by aadibajpai** [comment]
Can we report this to Discord? Like hey, you guys cut off songs > 128 characters

**Comment by flabbet** [comment]
Sure, we can try

**Comment by aadibajpai** [comment]
> Sure, we can try

In that case I'll reopen this so we don't just ignore it

**Comment by aadibajpai** [comment]
hmm rip discord ppl aren't taking issues these days
